version: "3.9"
services:
  compreface-db:
    container_name: ${COMPREFACE_DB_CONTAINER_NAME}
    image: postgres:11.5
    env_file:
      - ./config/.env
    restart: always
    networks:
      - openphoto
    environment:
      POSTGRES_USER: ${COMPREFACE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${COMPREFACE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${COMPREFACE_POSTGRES_DB}
    volumes:
      - ./${SERVICES_LOCATION}/${COMPREFACE_DB_DIRECTORY}:/var/lib/postgresql/data:rw

  compreface:
    build: ./${SERVICES_LOCATION}/${COMPREFACE_SERVICE_DIR}/.
    restart: always
    container_name: ${COMPREFACE_CONTAINER_NAME}
    networks:
      - openphoto
    ports:
      - "${COMPREFACE_PORT}:80"
    environment:
      POSTGRES_USER: ${COMPREFACE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${COMPREFACE_POSTGRES_PASSWORD}
      POSTGRES_URL: ${COMPREFACE_POSTGRES_URL}
      EXTERNAL_DB: ${COMPREFACE_EXTERNAL_DB}
    depends_on:
      - compreface-db

  redis:
    container_name: openphoto-redis
    image: redis:alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 100M
        reservations:
          cpus: "0.5"
          memory: 50M
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - openphoto
    command: >
      --requirepass ${REDIS_PASSWORD}
      --include /usr/local/etc/redis/redis.local.conf
    volumes:
      - ${REDIS_CONFIG_FILE}:/usr/local/etc/redis/redis.local.conf
      - redis-cache-openphoto:/data

networks:
  openphoto:
    external: true

volumes:
  redis-cache-openphoto:
    driver: local
